version: '3'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./:/server/
    labels:
      - "traefik.http.routers.php.rule=Host(`api.26.muffin.pm`)"
    
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: canard
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ~/datadir/mysql:/var/lib/mysql
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:8081
    labels:
      - "traefik.http.routers.backend.rule=Host(`pma.26.muffin.pm`)"

networks:
  default:
    external:
      name: "frontweb_default"

