version: '3'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/server/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`api.26.muffin.pm`)"
      - "traefik.docker.network=frontend_default"
      - "traefik.http.routers.php.entrypoints=web"
      - "traefik.http.services.php.loadbalancer.server.port=8000"
    
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - /datadir/mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`api.26.muffin.pm`)"
      - "traefik.docker.network=frontend_default"
      - "traefik.http.routers.pma.entrypoints=entrypma"
      - "traefik.http.services.pma.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: "frontweb_default"

