name: composer-update
on:
  workflow_dispatch:

jobs:
  composer-install:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Update db
      run: |
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd /server && docker-compose exec php composer install"
    
